### ISSUE TITLE
Demo not working.

### ISSUE THREAD

**Issue by zgbkdlm** [filtron/MarkovKernels.jl#57]
https://github.com/filtron/MarkovKernels.jl/blob/main/demo/sample_trajectory.jl:

Lines 13 and 17, `I` is not defined.

Line 20, `sample` not defined.

**Comment by filtron** [comment]
Yeah the ```/demo``` is mostly to develop demonstrations in the documentation. That is the following  code example should work:  https://filtron.github.io/MarkovKernels.jl/stable/tutorial_pomp_sampling/

If you really want to run the demo files, then I would recommend ```include("sampling_demo.jl")``` is what you want, this file calls ```include``` on ```sampling_implementation.jl``` and ```sample_trajectory.jl```, the former defined the function ```sample```. Additionally, you would have to add ```using LinearAlgebra``` e.g. in ```sampling_demo.jl```. 

Apparently I dont notice this error because I have ```using LinearAlgebra``` in my startup file. Sorry for this.
